'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ThemTieuChi

    '''<summary>txtTen control.</summary>
    Protected WithEvents txtTen As Global.System.Web.UI.WebControls.TextBox

    '''<summary>btnLuu control.</summary>
    Protected WithEvents btnLuu As Global.System.Web.UI.WebControls.Button

    '''<summary>rptTieuChi control.</summary>
    Protected WithEvents rptTieuChi As Global.System.Web.UI.WebControls.Repeater

End Class
