'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class KetQuaKhaoSat

    '''<summary>litTong control.</summary>
    Protected WithEvents litTong As Global.System.Web.UI.WebControls.Literal

    '''<summary>litDiemTB control.</summary>
    Protected WithEvents litDiemTB As Global.System.Web.UI.WebControls.Literal

    '''<summary>litPctHaiLong control.</summary>
    Protected WithEvents litPctHaiLong As Global.System.Web.UI.WebControls.Literal

    '''<summary>litPctTiepTuc control.</summary>
    Protected WithEvents litPctTiepTuc As Global.System.Web.UI.WebControls.Literal

    '''<summary>btnExcel control.</summary>
    Protected WithEvents btnExcel As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>pnlEmpty control.</summary>
    Protected WithEvents pnlEmpty As Global.System.Web.UI.WebControls.Panel

    '''<summary>pnlTable control.</summary>
    Protected WithEvents pnlTable As Global.System.Web.UI.WebControls.Panel

    '''<summary>rptPhieu control.</summary>
    Protected WithEvents rptPhieu As Global.System.Web.UI.WebControls.Repeater

    '''<summary>litJson control.</summary>
    Protected WithEvents litJson As Global.System.Web.UI.WebControls.Literal

End Class
