'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class KhaoSat

    '''<summary>txtHoTen control.</summary>
    Protected WithEvents txtHoTen As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtChucVu control.</summary>
    Protected WithEvents txtChucVu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtCongTy control.</summary>
    Protected WithEvents txtCongTy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtLienHe control.</summary>
    Protected WithEvents txtLienHe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtDichVu control.</summary>
    Protected WithEvents txtDichVu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtTenTau control.</summary>
    Protected WithEvents txtTenTau As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtLoaiHang control.</summary>
    Protected WithEvents txtLoaiHang As Global.System.Web.UI.WebControls.TextBox

    '''<summary>txtThoiGian control.</summary>
    Protected WithEvents txtThoiGian As Global.System.Web.UI.WebControls.TextBox

    '''<summary>rptNhom control.</summary>
    Protected WithEvents rptNhom As Global.System.Web.UI.WebControls.Repeater

    '''<summary>btnGui control.</summary>
    Protected WithEvents btnGui As Global.System.Web.UI.WebControls.Button
End Class
